missionProject/settings.py, missionProject/templates/base.html, missionProject/urls.py, search/admin.py, search/apps.py, search/models.py, search/templates/search_result.html, search/tests.py, search/views.py
네비바에 해시태그 검색기능 및
검색 결과값 없을 시 예외처리하여 화면 출력 구현 완료
=> 해시태그 검색기능 구현. 검색 결과값 없을 시 예외처리기능 구현.

freeBoard/templates/board.html, freeBoard/views.py
=> 자유게시판 페이지네이터 ㅎㅎ

freeBoard/views.py, request/templates/request_home.html, request/views.py
=>  페이지네이션 역순으로

main/templates/home.html, request/templates/detail.html
핫유저, 의뢰게시판 글 작성자, 댓글 작성자 클릭 시 해당 유저페이지로 이동하기 구현.
=> 핫유저, 의뢰게시판 글 작성자, 댓글 작성자 클릭 시 해당 유저페이지로 이동하기 구현.

main/context_processors.py, main/templates/home.html, main/views.py, missionProject/templates/base.html
home.html 기타 코드수정
최신의뢰글 detail페이지로 넘어갈 수 있도록 a태그 적용
=> home.html 기타 코드수정. 최신의뢰글 detail페이지로 넘어갈 수 있도록 a태그 적용

mypage/templates/chatting.html, mypage/templates/performing.html, mypage/templates/profile.html, mypage/views.py, request/views.py
=> 채팅 및 기타에러 수정

requirements.txt
requirements.txt 업데이트
(pip install django-default-imagefield)
=> requirements 파일 업데이트

mypage/views.py, request/views.py
=> review error

main/templates/home.html, main/views.py, view_request/urls.py
=> 추천의뢰 딕셔너리로 받아서 해시태그 당 포스트로 출력

main/views.py
=> 추천의뢰 로그아웃 상태에서 에러 해결

main/views.py, mypage/templates/profile.html, request/templates/detail.html
프로필 및 의뢰게시판 이미지 크기조절
200 x 200 (pixel)
=> 프로필 및 의뢰게시판 이미지 크기조절

accounts/models.py, main/views.py, missionProject/templates/base.html, request/templates/detail.html
- superuser일때 추천의뢰 발생에러 해결
- superuser일때 네비바 myPage 보이지않게 수정
=> superuser일때 추천의뢰 발생에러 해결, myPage 보이지않게 수정

accounts/views.py, main/context_processors.py
계정 생성 시 디폴트이미지 지정.
superuser 생성 시 profile_id 값 'admin'으로 자동저장
=> 계정 생성 시 디폴트이미지 지정. superuser 생성 시 profile_id 값 'admin'으로 자동저장

mypage/templates/perform_end.html, mypage/templates/profile.html, mypage/templates/submission.html, mypage/views.py, request/templates/detail.html, request/templates/edit.html, request/views.py
file모델 수정 시 값이 none이라면 pass.(현재 데이터 유지). 
마이페이지 후기 조건문 오류 수정.
=> file모델 수정 시 값이 none이라면 pass.(현재 데이터 유지). 마이페이지 후기 조건문 오류 수정.

freeBoard/templates/b_detail.html, missionProject/templates/base.html, request/views.py
자유게시판 좋아요 오류 -> 자바스크립트 수정.
좋아요 유저 클릭 시 유저페이지로 넘어가게 적용.
=> 자유게시판 좋아요 오류 -> 자바스크립트 수정. 좋아요 유저 클릭 시 유저페이지로 넘어가게 적용.

mypage/views.py, request/templates/edit.html, request/views.py
의뢰게시판 해시태그 수정 -> 해시태그 생성기능.
모든 해시태그에서 체크박스로 추가할 수 있게.
=> 의뢰게시판 해시태그 수정 -> 해시태그 생성기능, 모든 해시태그에서 체크박스로 추가할 수 있게

missionProject/templates/base.html, request/templates/detail.html, request/views.py
의뢰게시판 scrap한 유저 popover로 표시하도록 자바스크립트 적용.
=> 의뢰게시판 scrap한 유저 popover로 표시하도록 자바스크립트 적용.

accounts/templates/signup.html, mypage/views.py
=> required 더추가

accounts/templates/signup.html, accounts/views.py, missionProject/templates/base.html
signup 해시태그 에러 수정, 대학교 자동완성 기능 추가.
-> 아직 signup 이미지 에러 있는듯
=> signup 해시태그 에러 수정, 대학교 자동완성 기능 추가.

accounts/templates/signup.html, accounts/views.py, missionProject/templates/base.html
=> 대학교 클릭 시 자동으로 이메일 채워지는 기능 구현.

accounts/templates/signup.html
=> 자바스크립트 signup.html 추가

main/templates/home.html
=> home.html 부트스트랩 적용 -> popover

request/templates/detail.html, request/templates/request_home.html, request/views.py
scrap 여부에 따라 버튼바뀜. 본인은 스크랩버튼 보이지 않게 수정.
=> scrap 여부에 따라 버튼바뀜. 본인은 스크랩버튼 보이지 않게 수정.

mypage/templates/chatting.html, mypage/templates/profile.html
쪽지기능 본인만 삭제,수정 가능하게. 
약간의 디자인 수정.
=> 쪽지기능 본인만 삭제,수정 가능하게. 약간의 디자인 수정.

request/templates/detail.html
=> 의뢰게시판 detail.html 코드 수정.

main/templates/home.html, main/views.py, request/templates/detail.html
검색바 제목검색 자유/의뢰게시판 별 연관검색기능 구현.
=> 검색바 제목검색 자유/의뢰게시판 별 연관검색기능 구현.

request/templates/detail.html
=> scrap기능 본인 게시물엔 사용되지 않게 수정.

freeBoard/templates/b_edit.html, freeBoard/templates/b_new.html, freeBoard/views.py, mypage/views.py
자유게시판 해시태그 기능 추가. 수정페이지 자바스크립트 함수 수정.
=> 자유게시판 해시태그 기능 추가. 수정페이지 자바스크립트 함수 수정.

freeBoard/templates/b_edit.html, request/templates/edit.html
=> 의뢰게시판 수정창 버튼 자바스크립트 적용

main/templates/home.html, missionProject/templates/base.html, search/templates/search_result.html, search/views.py
검색타입 체크박스에서 셀렉트메뉴로 수정. 
모든게시판 검색기능, 유저검색 기능 추가. 
관련 자바스크립트 추가.
=> 검색타입 체크박스에서 셀렉트메뉴로 수정. 모든게시판 검색기능, 유저검색 기능 추가. 자바스크립트 기능 추가.

main/urls.py
=> main화면 url 수정.

main/templates/home.html, main/views.py
=> 검색바 해시태그 연관검색 기능 구현
